### ISSUE TITLE
Product edit screen looks like error

### ISSUE THREAD

**Issue by cfoxeny** [similik/similik#50]
Hi,

I tried to create 1 product and then edit it. In editing screen I can not see product general information like when I create it. It shows "Attribute", "Advance price" , "Custom Options", "SEO" and "Images"

Thanks

**Comment by similik** [comment]
Hi @cfoxeny ,

Could you please share the information about browser you are using?
Is there any error you can see from server error log file?

Thanks

**Comment by cfoxeny** [comment]
@similik 

There is no error from error log.
I added var_dump($result) in this file: app/Similik/src/Module/Catalog/Middleware/Product/Edit/GeneralInfoMiddleware.php (Line 76)
I see this error message: "Cannot return null for non-nullable field Product.tax_class."

**Comment by similik** [comment]
Thanks @cfoxeny 

Closing issue
